spring.application.name=gateway-service
spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.gateway.server.webflux.routes[6].id=telegram-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://telegram-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/telegram/**
spring.cloud.gateway.server.webflux.routes[6].filters[0]=RewritePath=/api/telegram/(?<segment>.*), /v1/telegram/$\{segment}
